#include <assert.h>
#include <stdbool.h>
#include <stdio.h>

#include "../include/definitions.h"

int main()
{

    instruction code_sample[8] = {};

    code_sample[0] = (instruction){.operation = GET, .target = UP};
    code_sample[1] = (instruction){.operation = JOF, .target = ADJ};
    ((u8 *)code_sample)[2] = 7;
    code_sample[3] = (instruction){.operation = ADD, .target = ADJ};
    ((u8 *)code_sample)[4] = 1;
    code_sample[5] = (instruction){.operation = PUT, .target = ANY};
    code_sample[6] = (instruction){.operation = JMP, .target = NIL};
    code_sample[7] = (instruction){.operation = HALT, .target = NIL};

    const char *source = "get UP\n"
                         "jof end\n"
                         "add 1\n"
                         "put ANY\n"
                         "jmp NIL\n"
                         "end:\n"
                         "halt\n";

    void *bytecode = NULL;
    u8 bytecode_len = 0;

    if (!assemble_program(source, &bytecode, &bytecode_len))
        fprintf(stderr, "Assembly failed\n");
    else
        printf("Assembly succeeded, bytecode length: %d\n", bytecode_len);

    for (u8 i = 0; i < bytecode_len; i++)
        printf("%02X ", ((u8 *)bytecode)[i]);

    // compare sample and generated bytecode

    putchar('\n');

    if (bytecode_len != sizeof(code_sample))
    {
        fprintf(stderr, "Bytecode length mismatch\n");
        return 1;
    }

    for (u8 i = 0; i < bytecode_len; i++)
    {
        if (((u8 *)bytecode)[i] != ((u8 *)code_sample)[i])
        {
            fprintf(stderr, "Bytecode mismatch at index %d: %02X != %02X\n", i, ((u8 *)bytecode)[i],
                    ((u8 *)code_sample)[i]);
        }
    }

    // return 0;

    grid g = initialize_grid(1, 2);

#define LEN 1

    u8 test[LEN] = {10};
    u8 out[LEN] = {};

    attach_input(&g, up, 0, test, sizeof(test));
    attach_output(&g, down, 0, out, sizeof(out));

    // load_program(&g, 0, 0, code_sample, sizeof(code_sample));
    // load_program(&g, 0, 1, code_sample, sizeof(code_sample));
    load_program(&g, 0, 0, bytecode, bytecode_len);
    load_program(&g, 0, 1, bytecode, bytecode_len);

    run_grid(&g, 32);

    free_grid(&g);

    for (u8 i = 0; i < sizeof(test); i++)
        printf("%d -> %d\n", test[i], out[i]);

    //     return 0;
}